# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c206511fe9e6fba37ae8e32f9100e424c7d1ccecb31cdff36c8a241f79d91ead67d10937d7d036e1211a2af1333e85a87f4d6b7577dbe494a9e7c44a0190794

test:
  secret_key_base: 6cd2f8a329cfdca9dfcc12fb4b3732b394ab5b942a47989ef0d332336a2870b3d89dbdbf55f9695d346dc557bc041f059fc10e57577124bfd6ee85fe63ca9346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
